/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardStudentRouteImport } from './routes/dashboard/student'
import { Route as DashboardRegistrarRouteImport } from './routes/dashboard/registrar'
import { Route as DashboardFinanceRouteImport } from './routes/dashboard/finance'
import { Route as DashboardFacultyRouteImport } from './routes/dashboard/faculty'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardStudentIndexRouteImport } from './routes/dashboard/student.index'
import { Route as DashboardRegistrarIndexRouteImport } from './routes/dashboard/registrar.index'
import { Route as DashboardFinanceIndexRouteImport } from './routes/dashboard/finance.index'
import { Route as DashboardFacultyIndexRouteImport } from './routes/dashboard/faculty.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin.index'
import { Route as DashboardStudentScheduleRouteImport } from './routes/dashboard/student.schedule'
import { Route as DashboardStudentGradesRouteImport } from './routes/dashboard/student.grades'
import { Route as DashboardStudentFinancesRouteImport } from './routes/dashboard/student.finances'
import { Route as DashboardStudentEnrollmentRouteImport } from './routes/dashboard/student.enrollment'
import { Route as DashboardRegistrarTranscriptsRouteImport } from './routes/dashboard/registrar.transcripts'
import { Route as DashboardRegistrarRegistrationsRouteImport } from './routes/dashboard/registrar.registrations'
import { Route as DashboardRegistrarRecordsRouteImport } from './routes/dashboard/registrar.records'
import { Route as DashboardRegistrarEnrollmentRouteImport } from './routes/dashboard/registrar.enrollment'
import { Route as DashboardFinanceReportsRouteImport } from './routes/dashboard/finance.reports'
import { Route as DashboardFinancePaymentsRouteImport } from './routes/dashboard/finance.payments'
import { Route as DashboardFinanceClearanceRouteImport } from './routes/dashboard/finance.clearance'
import { Route as DashboardFinanceAccountsRouteImport } from './routes/dashboard/finance.accounts'
import { Route as DashboardFacultyClassesRouteImport } from './routes/dashboard/faculty.classes'
import { Route as DashboardFacultyAttendanceRouteImport } from './routes/dashboard/faculty.attendance'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin.users'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard/admin.settings'
import { Route as DashboardAdminSecurityRouteImport } from './routes/dashboard/admin.security'
import { Route as DashboardAdminAnalyticsRouteImport } from './routes/dashboard/admin.analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegistrarRoute = DashboardRegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceRoute = DashboardFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFacultyRoute = DashboardFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentIndexRoute = DashboardStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardRegistrarIndexRoute = DashboardRegistrarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRegistrarRoute,
} as any)
const DashboardFinanceIndexRoute = DashboardFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardFinanceRoute,
} as any)
const DashboardFacultyIndexRoute = DashboardFacultyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardFacultyRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardStudentScheduleRoute =
  DashboardStudentScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardStudentGradesRoute = DashboardStudentGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentFinancesRoute =
  DashboardStudentFinancesRouteImport.update({
    id: '/finances',
    path: '/finances',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardStudentEnrollmentRoute =
  DashboardStudentEnrollmentRouteImport.update({
    id: '/enrollment',
    path: '/enrollment',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardRegistrarTranscriptsRoute =
  DashboardRegistrarTranscriptsRouteImport.update({
    id: '/transcripts',
    path: '/transcripts',
    getParentRoute: () => DashboardRegistrarRoute,
  } as any)
const DashboardRegistrarRegistrationsRoute =
  DashboardRegistrarRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => DashboardRegistrarRoute,
  } as any)
const DashboardRegistrarRecordsRoute =
  DashboardRegistrarRecordsRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => DashboardRegistrarRoute,
  } as any)
const DashboardRegistrarEnrollmentRoute =
  DashboardRegistrarEnrollmentRouteImport.update({
    id: '/enrollment',
    path: '/enrollment',
    getParentRoute: () => DashboardRegistrarRoute,
  } as any)
const DashboardFinanceReportsRoute = DashboardFinanceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardFinanceRoute,
} as any)
const DashboardFinancePaymentsRoute =
  DashboardFinancePaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => DashboardFinanceRoute,
  } as any)
const DashboardFinanceClearanceRoute =
  DashboardFinanceClearanceRouteImport.update({
    id: '/clearance',
    path: '/clearance',
    getParentRoute: () => DashboardFinanceRoute,
  } as any)
const DashboardFinanceAccountsRoute =
  DashboardFinanceAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => DashboardFinanceRoute,
  } as any)
const DashboardFacultyClassesRoute = DashboardFacultyClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => DashboardFacultyRoute,
} as any)
const DashboardFacultyAttendanceRoute =
  DashboardFacultyAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => DashboardFacultyRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSecurityRoute = DashboardAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminAnalyticsRoute = DashboardAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/register': typeof RegisterRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/faculty': typeof DashboardFacultyRouteWithChildren
  '/dashboard/finance': typeof DashboardFinanceRouteWithChildren
  '/dashboard/registrar': typeof DashboardRegistrarRouteWithChildren
  '/dashboard/student': typeof DashboardStudentRouteWithChildren
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/security': typeof DashboardAdminSecurityRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/faculty/attendance': typeof DashboardFacultyAttendanceRoute
  '/dashboard/faculty/classes': typeof DashboardFacultyClassesRoute
  '/dashboard/finance/accounts': typeof DashboardFinanceAccountsRoute
  '/dashboard/finance/clearance': typeof DashboardFinanceClearanceRoute
  '/dashboard/finance/payments': typeof DashboardFinancePaymentsRoute
  '/dashboard/finance/reports': typeof DashboardFinanceReportsRoute
  '/dashboard/registrar/enrollment': typeof DashboardRegistrarEnrollmentRoute
  '/dashboard/registrar/records': typeof DashboardRegistrarRecordsRoute
  '/dashboard/registrar/registrations': typeof DashboardRegistrarRegistrationsRoute
  '/dashboard/registrar/transcripts': typeof DashboardRegistrarTranscriptsRoute
  '/dashboard/student/enrollment': typeof DashboardStudentEnrollmentRoute
  '/dashboard/student/finances': typeof DashboardStudentFinancesRoute
  '/dashboard/student/grades': typeof DashboardStudentGradesRoute
  '/dashboard/student/schedule': typeof DashboardStudentScheduleRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/faculty/': typeof DashboardFacultyIndexRoute
  '/dashboard/finance/': typeof DashboardFinanceIndexRoute
  '/dashboard/registrar/': typeof DashboardRegistrarIndexRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/register': typeof RegisterRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/security': typeof DashboardAdminSecurityRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/faculty/attendance': typeof DashboardFacultyAttendanceRoute
  '/dashboard/faculty/classes': typeof DashboardFacultyClassesRoute
  '/dashboard/finance/accounts': typeof DashboardFinanceAccountsRoute
  '/dashboard/finance/clearance': typeof DashboardFinanceClearanceRoute
  '/dashboard/finance/payments': typeof DashboardFinancePaymentsRoute
  '/dashboard/finance/reports': typeof DashboardFinanceReportsRoute
  '/dashboard/registrar/enrollment': typeof DashboardRegistrarEnrollmentRoute
  '/dashboard/registrar/records': typeof DashboardRegistrarRecordsRoute
  '/dashboard/registrar/registrations': typeof DashboardRegistrarRegistrationsRoute
  '/dashboard/registrar/transcripts': typeof DashboardRegistrarTranscriptsRoute
  '/dashboard/student/enrollment': typeof DashboardStudentEnrollmentRoute
  '/dashboard/student/finances': typeof DashboardStudentFinancesRoute
  '/dashboard/student/grades': typeof DashboardStudentGradesRoute
  '/dashboard/student/schedule': typeof DashboardStudentScheduleRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/faculty': typeof DashboardFacultyIndexRoute
  '/dashboard/finance': typeof DashboardFinanceIndexRoute
  '/dashboard/registrar': typeof DashboardRegistrarIndexRoute
  '/dashboard/student': typeof DashboardStudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/register': typeof RegisterRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/faculty': typeof DashboardFacultyRouteWithChildren
  '/dashboard/finance': typeof DashboardFinanceRouteWithChildren
  '/dashboard/registrar': typeof DashboardRegistrarRouteWithChildren
  '/dashboard/student': typeof DashboardStudentRouteWithChildren
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/security': typeof DashboardAdminSecurityRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/faculty/attendance': typeof DashboardFacultyAttendanceRoute
  '/dashboard/faculty/classes': typeof DashboardFacultyClassesRoute
  '/dashboard/finance/accounts': typeof DashboardFinanceAccountsRoute
  '/dashboard/finance/clearance': typeof DashboardFinanceClearanceRoute
  '/dashboard/finance/payments': typeof DashboardFinancePaymentsRoute
  '/dashboard/finance/reports': typeof DashboardFinanceReportsRoute
  '/dashboard/registrar/enrollment': typeof DashboardRegistrarEnrollmentRoute
  '/dashboard/registrar/records': typeof DashboardRegistrarRecordsRoute
  '/dashboard/registrar/registrations': typeof DashboardRegistrarRegistrationsRoute
  '/dashboard/registrar/transcripts': typeof DashboardRegistrarTranscriptsRoute
  '/dashboard/student/enrollment': typeof DashboardStudentEnrollmentRoute
  '/dashboard/student/finances': typeof DashboardStudentFinancesRoute
  '/dashboard/student/grades': typeof DashboardStudentGradesRoute
  '/dashboard/student/schedule': typeof DashboardStudentScheduleRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/faculty/': typeof DashboardFacultyIndexRoute
  '/dashboard/finance/': typeof DashboardFinanceIndexRoute
  '/dashboard/registrar/': typeof DashboardRegistrarIndexRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/faculty'
    | '/dashboard/finance'
    | '/dashboard/registrar'
    | '/dashboard/student'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/security'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/faculty/attendance'
    | '/dashboard/faculty/classes'
    | '/dashboard/finance/accounts'
    | '/dashboard/finance/clearance'
    | '/dashboard/finance/payments'
    | '/dashboard/finance/reports'
    | '/dashboard/registrar/enrollment'
    | '/dashboard/registrar/records'
    | '/dashboard/registrar/registrations'
    | '/dashboard/registrar/transcripts'
    | '/dashboard/student/enrollment'
    | '/dashboard/student/finances'
    | '/dashboard/student/grades'
    | '/dashboard/student/schedule'
    | '/dashboard/admin/'
    | '/dashboard/faculty/'
    | '/dashboard/finance/'
    | '/dashboard/registrar/'
    | '/dashboard/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/register'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/security'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/faculty/attendance'
    | '/dashboard/faculty/classes'
    | '/dashboard/finance/accounts'
    | '/dashboard/finance/clearance'
    | '/dashboard/finance/payments'
    | '/dashboard/finance/reports'
    | '/dashboard/registrar/enrollment'
    | '/dashboard/registrar/records'
    | '/dashboard/registrar/registrations'
    | '/dashboard/registrar/transcripts'
    | '/dashboard/student/enrollment'
    | '/dashboard/student/finances'
    | '/dashboard/student/grades'
    | '/dashboard/student/schedule'
    | '/dashboard/admin'
    | '/dashboard/faculty'
    | '/dashboard/finance'
    | '/dashboard/registrar'
    | '/dashboard/student'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/faculty'
    | '/dashboard/finance'
    | '/dashboard/registrar'
    | '/dashboard/student'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/security'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/faculty/attendance'
    | '/dashboard/faculty/classes'
    | '/dashboard/finance/accounts'
    | '/dashboard/finance/clearance'
    | '/dashboard/finance/payments'
    | '/dashboard/finance/reports'
    | '/dashboard/registrar/enrollment'
    | '/dashboard/registrar/records'
    | '/dashboard/registrar/registrations'
    | '/dashboard/registrar/transcripts'
    | '/dashboard/student/enrollment'
    | '/dashboard/student/finances'
    | '/dashboard/student/grades'
    | '/dashboard/student/schedule'
    | '/dashboard/admin/'
    | '/dashboard/faculty/'
    | '/dashboard/finance/'
    | '/dashboard/registrar/'
    | '/dashboard/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/registrar': {
      id: '/dashboard/registrar'
      path: '/registrar'
      fullPath: '/dashboard/registrar'
      preLoaderRoute: typeof DashboardRegistrarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/finance': {
      id: '/dashboard/finance'
      path: '/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof DashboardFinanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/faculty': {
      id: '/dashboard/faculty'
      path: '/faculty'
      fullPath: '/dashboard/faculty'
      preLoaderRoute: typeof DashboardFacultyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/': {
      id: '/dashboard/student/'
      path: '/'
      fullPath: '/dashboard/student/'
      preLoaderRoute: typeof DashboardStudentIndexRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/registrar/': {
      id: '/dashboard/registrar/'
      path: '/'
      fullPath: '/dashboard/registrar/'
      preLoaderRoute: typeof DashboardRegistrarIndexRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/finance/': {
      id: '/dashboard/finance/'
      path: '/'
      fullPath: '/dashboard/finance/'
      preLoaderRoute: typeof DashboardFinanceIndexRouteImport
      parentRoute: typeof DashboardFinanceRoute
    }
    '/dashboard/faculty/': {
      id: '/dashboard/faculty/'
      path: '/'
      fullPath: '/dashboard/faculty/'
      preLoaderRoute: typeof DashboardFacultyIndexRouteImport
      parentRoute: typeof DashboardFacultyRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/student/schedule': {
      id: '/dashboard/student/schedule'
      path: '/schedule'
      fullPath: '/dashboard/student/schedule'
      preLoaderRoute: typeof DashboardStudentScheduleRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/grades': {
      id: '/dashboard/student/grades'
      path: '/grades'
      fullPath: '/dashboard/student/grades'
      preLoaderRoute: typeof DashboardStudentGradesRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/finances': {
      id: '/dashboard/student/finances'
      path: '/finances'
      fullPath: '/dashboard/student/finances'
      preLoaderRoute: typeof DashboardStudentFinancesRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/enrollment': {
      id: '/dashboard/student/enrollment'
      path: '/enrollment'
      fullPath: '/dashboard/student/enrollment'
      preLoaderRoute: typeof DashboardStudentEnrollmentRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/registrar/transcripts': {
      id: '/dashboard/registrar/transcripts'
      path: '/transcripts'
      fullPath: '/dashboard/registrar/transcripts'
      preLoaderRoute: typeof DashboardRegistrarTranscriptsRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/registrar/registrations': {
      id: '/dashboard/registrar/registrations'
      path: '/registrations'
      fullPath: '/dashboard/registrar/registrations'
      preLoaderRoute: typeof DashboardRegistrarRegistrationsRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/registrar/records': {
      id: '/dashboard/registrar/records'
      path: '/records'
      fullPath: '/dashboard/registrar/records'
      preLoaderRoute: typeof DashboardRegistrarRecordsRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/registrar/enrollment': {
      id: '/dashboard/registrar/enrollment'
      path: '/enrollment'
      fullPath: '/dashboard/registrar/enrollment'
      preLoaderRoute: typeof DashboardRegistrarEnrollmentRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/finance/reports': {
      id: '/dashboard/finance/reports'
      path: '/reports'
      fullPath: '/dashboard/finance/reports'
      preLoaderRoute: typeof DashboardFinanceReportsRouteImport
      parentRoute: typeof DashboardFinanceRoute
    }
    '/dashboard/finance/payments': {
      id: '/dashboard/finance/payments'
      path: '/payments'
      fullPath: '/dashboard/finance/payments'
      preLoaderRoute: typeof DashboardFinancePaymentsRouteImport
      parentRoute: typeof DashboardFinanceRoute
    }
    '/dashboard/finance/clearance': {
      id: '/dashboard/finance/clearance'
      path: '/clearance'
      fullPath: '/dashboard/finance/clearance'
      preLoaderRoute: typeof DashboardFinanceClearanceRouteImport
      parentRoute: typeof DashboardFinanceRoute
    }
    '/dashboard/finance/accounts': {
      id: '/dashboard/finance/accounts'
      path: '/accounts'
      fullPath: '/dashboard/finance/accounts'
      preLoaderRoute: typeof DashboardFinanceAccountsRouteImport
      parentRoute: typeof DashboardFinanceRoute
    }
    '/dashboard/faculty/classes': {
      id: '/dashboard/faculty/classes'
      path: '/classes'
      fullPath: '/dashboard/faculty/classes'
      preLoaderRoute: typeof DashboardFacultyClassesRouteImport
      parentRoute: typeof DashboardFacultyRoute
    }
    '/dashboard/faculty/attendance': {
      id: '/dashboard/faculty/attendance'
      path: '/attendance'
      fullPath: '/dashboard/faculty/attendance'
      preLoaderRoute: typeof DashboardFacultyAttendanceRouteImport
      parentRoute: typeof DashboardFacultyRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/security': {
      id: '/dashboard/admin/security'
      path: '/security'
      fullPath: '/dashboard/admin/security'
      preLoaderRoute: typeof DashboardAdminSecurityRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/analytics': {
      id: '/dashboard/admin/analytics'
      path: '/analytics'
      fullPath: '/dashboard/admin/analytics'
      preLoaderRoute: typeof DashboardAdminAnalyticsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminAnalyticsRoute: typeof DashboardAdminAnalyticsRoute
  DashboardAdminSecurityRoute: typeof DashboardAdminSecurityRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminAnalyticsRoute: DashboardAdminAnalyticsRoute,
  DashboardAdminSecurityRoute: DashboardAdminSecurityRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardFacultyRouteChildren {
  DashboardFacultyAttendanceRoute: typeof DashboardFacultyAttendanceRoute
  DashboardFacultyClassesRoute: typeof DashboardFacultyClassesRoute
  DashboardFacultyIndexRoute: typeof DashboardFacultyIndexRoute
}

const DashboardFacultyRouteChildren: DashboardFacultyRouteChildren = {
  DashboardFacultyAttendanceRoute: DashboardFacultyAttendanceRoute,
  DashboardFacultyClassesRoute: DashboardFacultyClassesRoute,
  DashboardFacultyIndexRoute: DashboardFacultyIndexRoute,
}

const DashboardFacultyRouteWithChildren =
  DashboardFacultyRoute._addFileChildren(DashboardFacultyRouteChildren)

interface DashboardFinanceRouteChildren {
  DashboardFinanceAccountsRoute: typeof DashboardFinanceAccountsRoute
  DashboardFinanceClearanceRoute: typeof DashboardFinanceClearanceRoute
  DashboardFinancePaymentsRoute: typeof DashboardFinancePaymentsRoute
  DashboardFinanceReportsRoute: typeof DashboardFinanceReportsRoute
  DashboardFinanceIndexRoute: typeof DashboardFinanceIndexRoute
}

const DashboardFinanceRouteChildren: DashboardFinanceRouteChildren = {
  DashboardFinanceAccountsRoute: DashboardFinanceAccountsRoute,
  DashboardFinanceClearanceRoute: DashboardFinanceClearanceRoute,
  DashboardFinancePaymentsRoute: DashboardFinancePaymentsRoute,
  DashboardFinanceReportsRoute: DashboardFinanceReportsRoute,
  DashboardFinanceIndexRoute: DashboardFinanceIndexRoute,
}

const DashboardFinanceRouteWithChildren =
  DashboardFinanceRoute._addFileChildren(DashboardFinanceRouteChildren)

interface DashboardRegistrarRouteChildren {
  DashboardRegistrarEnrollmentRoute: typeof DashboardRegistrarEnrollmentRoute
  DashboardRegistrarRecordsRoute: typeof DashboardRegistrarRecordsRoute
  DashboardRegistrarRegistrationsRoute: typeof DashboardRegistrarRegistrationsRoute
  DashboardRegistrarTranscriptsRoute: typeof DashboardRegistrarTranscriptsRoute
  DashboardRegistrarIndexRoute: typeof DashboardRegistrarIndexRoute
}

const DashboardRegistrarRouteChildren: DashboardRegistrarRouteChildren = {
  DashboardRegistrarEnrollmentRoute: DashboardRegistrarEnrollmentRoute,
  DashboardRegistrarRecordsRoute: DashboardRegistrarRecordsRoute,
  DashboardRegistrarRegistrationsRoute: DashboardRegistrarRegistrationsRoute,
  DashboardRegistrarTranscriptsRoute: DashboardRegistrarTranscriptsRoute,
  DashboardRegistrarIndexRoute: DashboardRegistrarIndexRoute,
}

const DashboardRegistrarRouteWithChildren =
  DashboardRegistrarRoute._addFileChildren(DashboardRegistrarRouteChildren)

interface DashboardStudentRouteChildren {
  DashboardStudentEnrollmentRoute: typeof DashboardStudentEnrollmentRoute
  DashboardStudentFinancesRoute: typeof DashboardStudentFinancesRoute
  DashboardStudentGradesRoute: typeof DashboardStudentGradesRoute
  DashboardStudentScheduleRoute: typeof DashboardStudentScheduleRoute
  DashboardStudentIndexRoute: typeof DashboardStudentIndexRoute
}

const DashboardStudentRouteChildren: DashboardStudentRouteChildren = {
  DashboardStudentEnrollmentRoute: DashboardStudentEnrollmentRoute,
  DashboardStudentFinancesRoute: DashboardStudentFinancesRoute,
  DashboardStudentGradesRoute: DashboardStudentGradesRoute,
  DashboardStudentScheduleRoute: DashboardStudentScheduleRoute,
  DashboardStudentIndexRoute: DashboardStudentIndexRoute,
}

const DashboardStudentRouteWithChildren =
  DashboardStudentRoute._addFileChildren(DashboardStudentRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardFacultyRoute: typeof DashboardFacultyRouteWithChildren
  DashboardFinanceRoute: typeof DashboardFinanceRouteWithChildren
  DashboardRegistrarRoute: typeof DashboardRegistrarRouteWithChildren
  DashboardStudentRoute: typeof DashboardStudentRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardFacultyRoute: DashboardFacultyRouteWithChildren,
  DashboardFinanceRoute: DashboardFinanceRouteWithChildren,
  DashboardRegistrarRoute: DashboardRegistrarRouteWithChildren,
  DashboardStudentRoute: DashboardStudentRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
